### ISSUE TITLE
NPM and coffeescript error on startup

### ISSUE THREAD

**Issue by mandymozart** [bergie/blogsiple#4]
Hi, 

I am desperately trying to set up blogsiple

and am stuck with a supposingly npm error message:

```
hana (master) blogsiple$ ./bin/blogsiple

fs.js:356
  binding.mkdir(path, modeNum(mode), callback || noop);
          ^
TypeError: Bad argument
    at Object.mkdir (fs.js:356:11)
    at /home/hana/RubymineProjects/blogsiple/lib/blogsiple.coffee:19:15
```

Dependencies:

```
npm --version
1.0.106

coffee --version
CoffeeScript version 1.1.1

node --version
v0.4.9
```

any advice? I might be very stupid but am trying 
my history installing:

git clone git://github.com/bergie/blogsiple.git
  229  cd blogsiple/
  230  ls
  231  git submodule update --init
  234  npm install
  235  ./bin/blogsiple
  236  which coffee
  237  coffee --version
  238  sudo apt-get install coffeescript
  239  which coffee
  240  which node
  241  ./bin/blogsiple
  242  npm install redis
  243  ./bin/blogsiple
  244  npm install -g --prefix ./foo/bar abbrev
  245  ./bin/blogsiple
  246  npm --version
  247  coffee --version
  248  node
  249  node --version
  250  ls
  251  npm update
  252  npm update npm
  253  curl http://npmjs.org/install.sh | sh
  254  ./bin/blogsiple
  255  history

**Comment by mandymozart** [comment]
thx.

**Comment by bergie** [comment]
Blogsiple has recently been refactored to run under [NodeXT](https://github.com/bergie/nodext). Can you try again?

Please reopen if this still persists.
