### ISSUE TITLE
doesn't seem to include editable.js

### ISSUE THREAD

**Issue by reedobrien** [bergie/blogsiple#5]
in:

```
views/layout.jade:    script(src='/js/editable.js')
```

but there is no static/js directory and so trying to reach js/editable.js results in 500 error:

```
Error: ENOENT, no such file or directory '/path/to/blogsiple/lib/../static/js/editable.js'
```

**Comment by bergie** [comment]
This should be auto-generated with the Express `compiler` from `lib/static/js/editable.coffee` thanks to this directive:

```
server.use '/', http.compiler
  src: "#{__dirname}/static"
  dest: "#{__dirname}/../static"
  enable: ['coffeescript', 'sass']
```

**Comment by reedobrien** [comment]
Sass seems to work and creates the blogsiple.css but no love on the coffeescript. Here are versions FWIW, I suspect an incompatibility:

```
blogsiple@0.0.1 /tmp/node/blogsiple
|-- coffee-script@1.2.0 
|-- connect-conneg@0.1.1 
|-- express@2.5.8 
| |-- connect@1.8.5 
| | |__ formidable@1.0.8 
| |-- mime@1.2.4 
| |-- mkdirp@0.3.0 
| |__ qs@0.4.2 
|-- express-resource@0.2.4 
| |__ lingo@0.0.4 
|-- jade@0.20.1 
| |-- commander@0.5.2 
| |__ mkdirp@0.3.0 
|-- jugglingdb@0.1.0 
| |__ hashish@0.0.4 
|   |__ traverse@0.5.2 
|-- passport@0.1.6 
| |__ pkginfo@0.2.3 
|-- passport-browserid@0.1.0 
|-- redis@0.7.1  extraneous
|__ sass@0.5.0 
```

Thanks for your quick response. I am headed out of town and unfortunately can't look back at this for a while.

**Comment by bergie** [comment]
Got it, the directory has to exist before compiler has to do its work. This has been fixed as part of the rebasing on [NodeXT](https://github.com/bergie/nodext).
